### ISSUE TITLE
Cannot seem to be able to download the MoguTDA package

### ISSUE THREAD

**Issue by Fulguritude** [stephenhky/MoguTDA#9]
I get the following shell output:

```
Collecting mogutda
  Using cached mogutda-0.3.0.tar.gz (9.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i43vzm5w/mogutda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i43vzm5w/mogutda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fqvz4km0
         cwd: /tmp/pip-install-i43vzm5w/mogutda/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i43vzm5w/mogutda/setup.py", line 42, in <module>
        install_requires=install_requirements(),
      File "/tmp/pip-install-i43vzm5w/mogutda/setup.py", line 16, in install_requirements
        return [package_string.strip() for package_string in open('requirements.txt', 'r')]
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
```

Thanks

**Comment by stephenhky** [comment]
Thanks for pointing it out. It is a small bug in the repository script. I addressed it in this [commit](https://github.com/stephenhky/MoguTDA/commit/e6ff31d1d331d23c8e36dd18446f64476ff92c76).

The new release 0.3.1 has it fixed. You should encounter no issue by `pip` installing it now.
